//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.18 at 05:01:23 PM CET 
//


package it.istat.is2.xmlparser.domain;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the xmlparser2 package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xmlparser2
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml.Signature.OutputVariables }
     */
    public BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml.Signature.OutputVariables createBusinessServiceXmlAppServiceXmlInstancesStepInstanceXmlSignatureOutputVariables() {
        return new BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml.Signature.OutputVariables();
    }

    /**
     * Create an instance of {@link BusinessServiceXml }
     */
    public BusinessServiceXml createBusinessServiceXml() {
        return new BusinessServiceXml();
    }

    /**
     * Create an instance of {@link BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml.Signature.InputVariables }
     */
    public BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml.Signature.InputVariables createBusinessServiceXmlAppServiceXmlInstancesStepInstanceXmlSignatureInputVariables() {
        return new BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml.Signature.InputVariables();
    }

    /**
     * Create an instance of {@link BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml.Signature.OutputVariables.OutputVariable.Role }
     */
    public BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml.Signature.OutputVariables.OutputVariable.Role createBusinessServiceXmlAppServiceXmlInstancesStepInstanceXmlSignatureOutputVariablesOutputVariableRole() {
        return new BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml.Signature.OutputVariables.OutputVariable.Role();
    }

    /**
     * Create an instance of {@link BusinessServiceXml.AppServiceXml }
     */
    public BusinessServiceXml.AppServiceXml createBusinessServiceXmlAppServiceXml() {
        return new BusinessServiceXml.AppServiceXml();
    }

    /**
     * Create an instance of {@link BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml }
     */
    public BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml createBusinessServiceXmlAppServiceXmlInstancesStepInstanceXml() {
        return new BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml();
    }

    /**
     * Create an instance of {@link BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml.Signature.InputVariables.InputVariable.Role }
     */
    public BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml.Signature.InputVariables.InputVariable.Role createBusinessServiceXmlAppServiceXmlInstancesStepInstanceXmlSignatureInputVariablesInputVariableRole() {
        return new BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml.Signature.InputVariables.InputVariable.Role();
    }

    /**
     * Create an instance of {@link BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml.Signature }
     */
    public BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml.Signature createBusinessServiceXmlAppServiceXmlInstancesStepInstanceXmlSignature() {
        return new BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml.Signature();
    }

    /**
     * Create an instance of {@link BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml.Signature.OutputVariables.OutputVariable }
     */
    public BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml.Signature.OutputVariables.OutputVariable createBusinessServiceXmlAppServiceXmlInstancesStepInstanceXmlSignatureOutputVariablesOutputVariable() {
        return new BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml.Signature.OutputVariables.OutputVariable();
    }

    /**
     * Create an instance of {@link BusinessServiceXml.AppServiceXml.Instances }
     */
    public BusinessServiceXml.AppServiceXml.Instances createBusinessServiceXmlAppServiceXmlInstances() {
        return new BusinessServiceXml.AppServiceXml.Instances();
    }

    /**
     * Create an instance of {@link BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml.Signature.Parameters }
     */
    public BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml.Signature.Parameters createBusinessServiceXmlAppServiceXmlInstancesStepInstanceXmlSignatureParameters() {
        return new BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml.Signature.Parameters();
    }

    /**
     * Create an instance of {@link BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml.Signature.InputVariables.InputVariable }
     */
    public BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml.Signature.InputVariables.InputVariable createBusinessServiceXmlAppServiceXmlInstancesStepInstanceXmlSignatureInputVariablesInputVariable() {
        return new BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml.Signature.InputVariables.InputVariable();
    }

    /**
     * Create an instance of {@link BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml.Signature.Parameters.ParameterXml }
     */
    public BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml.Signature.Parameters.ParameterXml createBusinessServiceXmlAppServiceXmlInstancesStepInstanceXmlSignatureParametersParameterXml() {
        return new BusinessServiceXml.AppServiceXml.Instances.StepInstanceXml.Signature.Parameters.ParameterXml();
    }

}
