//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.14 at 01:22:49 PM CET 
//


package it.istat.is2.xmlparser.domain;

import javax.xml.bind.annotation.XmlRegistry;

import it.istat.is2.xmlparser.domain.Service.Methods;
import it.istat.is2.xmlparser.domain.Service.Methods.Method;
import it.istat.is2.xmlparser.domain.Service.Methods.Method.InputParameter;
import it.istat.is2.xmlparser.domain.Service.Methods.Method.InputVariable;
import it.istat.is2.xmlparser.domain.Service.Methods.Method.OutputVariable;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xmlparser package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xmlparser
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link Service.Methods.Method.OutputVariable }
     * 
     */
    public Service.Methods.Method.OutputVariable createServiceMethodsMethodOutputVariable() {
        return new Service.Methods.Method.OutputVariable();
    }

    /**
     * Create an instance of {@link Service.Methods.Method }
     * 
     */
    public Service.Methods.Method createServiceMethodsMethod() {
        return new Service.Methods.Method();
    }

    /**
     * Create an instance of {@link Service.Methods }
     * 
     */
    public Service.Methods createServiceMethods() {
        return new Service.Methods();
    }

    /**
     * Create an instance of {@link Service.Methods.Method.InputVariable }
     * 
     */
    public Service.Methods.Method.InputVariable createServiceMethodsMethodInputVariable() {
        return new Service.Methods.Method.InputVariable();
    }

    /**
     * Create an instance of {@link Service.Methods.Method.InputParameter }
     * 
     */
    public Service.Methods.Method.InputParameter createServiceMethodsMethodInputParameter() {
        return new Service.Methods.Method.InputParameter();
    }

} 
