//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.14 at 01:22:49 PM CET 
//


package it.istat.is2.xmlparser.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Shortname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Filename" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="Language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Methods">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Method" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Shortname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Input_Variable" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Order" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                                       &lt;element name="Shortname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Required" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Input_Parameter" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Order" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                                       &lt;element name="Shortname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Required" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Default" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Minvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Maxvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Output_Variable" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Ov_Order" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                                       &lt;element name="Ov_Shortnam" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="Ov_Shortname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="Ov_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Ov_Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Ov_Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "shortname",
    "name",
    "description",
    "filename",
    "language",
    "methods"
})
@XmlRootElement(name = "Service")
public class Service {

    @XmlElement(name = "Shortname", required = true)
    protected String shortname;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "Filename", required = true)
    protected Object filename;
    @XmlElement(name = "Language", required = true)
    protected String language;
    @XmlElement(name = "Methods", required = true)
    protected Service.Methods methods;

    /**
     * Gets the value of the shortname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortname(String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the filename property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getFilename() {
        return filename;
    }

    /**
     * Sets the value of the filename property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFilename(Object value) {
        this.filename = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the methods property.
     * 
     * @return
     *     possible object is
     *     {@link Service.Methods }
     *     
     */
    public Service.Methods getMethods() {
        return methods;
    }

    /**
     * Sets the value of the methods property.
     * 
     * @param value
     *     allowed object is
     *     {@link Service.Methods }
     *     
     */
    public void setMethods(Service.Methods value) {
        this.methods = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Method" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Shortname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Label" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Input_Variable" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Order" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                             &lt;element name="Shortname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Required" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Input_Parameter" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Order" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                             &lt;element name="Shortname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Required" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Default" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Minvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Maxvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Output_Variable" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Ov_Order" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                             &lt;element name="Ov_Shortnam" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="Ov_Shortname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="Ov_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Ov_Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Ov_Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "method"
    })
    public static class Methods {

        @XmlElement(name = "Method", required = true)
        protected List<Service.Methods.Method> method;

        /**
         * Gets the value of the method property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the method property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMethod().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Service.Methods.Method }
         * 
         * 
         */
        public List<Service.Methods.Method> getMethod() {
            if (method == null) {
                method = new ArrayList<Service.Methods.Method>();
            }
            return this.method;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Shortname" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Label" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Input_Variable" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Order" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *                   &lt;element name="Shortname" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Required" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Input_Parameter" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Order" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *                   &lt;element name="Shortname" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Required" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Default" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Minvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Maxvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Output_Variable" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Ov_Order" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *                   &lt;element name="Ov_Shortnam" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="Ov_Shortname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="Ov_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Ov_Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Ov_Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "shortname",
            "name",
            "description",
            "label",
            "inputVariable",
            "inputParameter",
            "outputVariable"
        })
        public static class Method {

            @XmlElement(name = "Shortname", required = true)
            protected String shortname;
            @XmlElement(name = "Name", required = true)
            protected String name;
            @XmlElement(name = "Description", required = true)
            protected String description;
            @XmlElement(name = "Label", required = true)
            protected String label;
            @XmlElement(name = "Input_Variable")
            protected List<Service.Methods.Method.InputVariable> inputVariable;
            @XmlElement(name = "Input_Parameter")
            protected List<Service.Methods.Method.InputParameter> inputParameter;
            @XmlElement(name = "Output_Variable")
            protected List<Service.Methods.Method.OutputVariable> outputVariable;

            /**
             * Gets the value of the shortname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getShortname() {
                return shortname;
            }

            /**
             * Sets the value of the shortname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setShortname(String value) {
                this.shortname = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the label property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLabel() {
                return label;
            }

            /**
             * Sets the value of the label property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLabel(String value) {
                this.label = value;
            }

            /**
             * Gets the value of the inputVariable property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the inputVariable property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getInputVariable().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Service.Methods.Method.InputVariable }
             * 
             * 
             */
            public List<Service.Methods.Method.InputVariable> getInputVariable() {
                if (inputVariable == null) {
                    inputVariable = new ArrayList<Service.Methods.Method.InputVariable>();
                }
                return this.inputVariable;
            }

            /**
             * Gets the value of the inputParameter property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the inputParameter property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getInputParameter().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Service.Methods.Method.InputParameter }
             * 
             * 
             */
            public List<Service.Methods.Method.InputParameter> getInputParameter() {
                if (inputParameter == null) {
                    inputParameter = new ArrayList<Service.Methods.Method.InputParameter>();
                }
                return this.inputParameter;
            }

            /**
             * Gets the value of the outputVariable property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the outputVariable property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getOutputVariable().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Service.Methods.Method.OutputVariable }
             * 
             * 
             */
            public List<Service.Methods.Method.OutputVariable> getOutputVariable() {
                if (outputVariable == null) {
                    outputVariable = new ArrayList<Service.Methods.Method.OutputVariable>();
                }
                return this.outputVariable;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Order" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
             *         &lt;element name="Shortname" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Required" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Default" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Minvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Maxvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "order",
                "shortname",
                "name",
                "description",
                "type",
                "required",
                "_default",
                "minvalue",
                "maxvalue"
            })
            public static class InputParameter {

                @XmlElement(name = "Order")
                @XmlSchemaType(name = "unsignedByte")
                protected short order;
                @XmlElement(name = "Shortname", required = true)
                protected String shortname;
                @XmlElement(name = "Name", required = true)
                protected String name;
                @XmlElement(name = "Description", required = true)
                protected String description;
                @XmlElement(name = "Type", required = true)
                protected String type;
                @XmlElement(name = "Required", required = true)
                protected String required;
                @XmlElement(name = "Default", required = true)
                protected String _default;
                @XmlElement(name = "Minvalue", required = true)
                protected String minvalue;
                @XmlElement(name = "Maxvalue", required = true)
                protected String maxvalue;

                /**
                 * Gets the value of the order property.
                 * 
                 */
                public short getOrder() {
                    return order;
                }

                /**
                 * Sets the value of the order property.
                 * 
                 */
                public void setOrder(short value) {
                    this.order = value;
                }

                /**
                 * Gets the value of the shortname property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getShortname() {
                    return shortname;
                }

                /**
                 * Sets the value of the shortname property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setShortname(String value) {
                    this.shortname = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the description property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDescription() {
                    return description;
                }

                /**
                 * Sets the value of the description property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDescription(String value) {
                    this.description = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

                /**
                 * Gets the value of the required property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRequired() {
                    return required;
                }

                /**
                 * Sets the value of the required property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRequired(String value) {
                    this.required = value;
                }

                /**
                 * Gets the value of the default property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDefault() {
                    return _default;
                }

                /**
                 * Sets the value of the default property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDefault(String value) {
                    this._default = value;
                }

                /**
                 * Gets the value of the minvalue property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMinvalue() {
                    return minvalue;
                }

                /**
                 * Sets the value of the minvalue property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMinvalue(String value) {
                    this.minvalue = value;
                }

                /**
                 * Gets the value of the maxvalue property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMaxvalue() {
                    return maxvalue;
                }

                /**
                 * Sets the value of the maxvalue property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMaxvalue(String value) {
                    this.maxvalue = value;
                }
                @Override
            	public String toString() {
            		return "InputParameter: [Order = " + order + ", Type = " + type + ", Description = " + description + ", Required = "
            				+ required + ", Maxvalue = " + maxvalue + ", Minvalue = " + minvalue + ", Shortname = " + shortname
            				+ ", Default = " + _default + ", Name = " + name + "]";
            	}

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Order" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
             *         &lt;element name="Shortname" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Required" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "order",
                "shortname",
                "name",
                "description",
                "type",
                "required"
            })
            public static class InputVariable {

                @XmlElement(name = "Order")
                @XmlSchemaType(name = "unsignedByte")
                protected short order;
                @XmlElement(name = "Shortname", required = true)
                protected String shortname;
                @XmlElement(name = "Name", required = true)
                protected String name;
                @XmlElement(name = "Description", required = true)
                protected String description;
                @XmlElement(name = "Type", required = true)
                protected String type;
                @XmlElement(name = "Required", required = true)
                protected String required;

                /**
                 * Gets the value of the order property.
                 * 
                 */
                public short getOrder() {
                    return order;
                }

                /**
                 * Sets the value of the order property.
                 * 
                 */
                public void setOrder(short value) {
                    this.order = value;
                }

                /**
                 * Gets the value of the shortname property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getShortname() {
                    return shortname;
                }

                /**
                 * Sets the value of the shortname property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setShortname(String value) {
                    this.shortname = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the description property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDescription() {
                    return description;
                }

                /**
                 * Sets the value of the description property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDescription(String value) {
                    this.description = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

                /**
                 * Gets the value of the required property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRequired() {
                    return required;
                }

                /**
                 * Sets the value of the required property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRequired(String value) {
                    this.required = value;
                }
                @Override
                public String toString()
                {
                    return "InputVariable: [Order = "+order+", Type = "+type+", Description = "+description+", Required = "+required+", Shortname = "+shortname+", Name = "+name+"]";
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Ov_Order" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
             *         &lt;element name="Ov_Shortnam" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="Ov_Shortname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="Ov_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Ov_Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Ov_Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "ovOrder",
                "ovShortnam",
                "ovShortname",
                "ovName",
                "ovDescription",
                "ovType"
            })
            public static class OutputVariable {

                @XmlElement(name = "Ov_Order")
                @XmlSchemaType(name = "unsignedByte")
                protected short ovOrder;
                @XmlElement(name = "Ov_Shortnam")
                protected String ovShortnam;
                @XmlElement(name = "Ov_Shortname")
                protected String ovShortname;
                @XmlElement(name = "Ov_Name", required = true)
                protected String ovName;
                @XmlElement(name = "Ov_Description", required = true)
                protected String ovDescription;
                @XmlElement(name = "Ov_Type", required = true)
                protected String ovType;

                /**
                 * Gets the value of the ovOrder property.
                 * 
                 */
                public short getOvOrder() {
                    return ovOrder;
                }

                /**
                 * Sets the value of the ovOrder property.
                 * 
                 */
                public void setOvOrder(short value) {
                    this.ovOrder = value;
                }

                /**
                 * Gets the value of the ovShortnam property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOvShortnam() {
                    return ovShortnam;
                }

                /**
                 * Sets the value of the ovShortnam property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOvShortnam(String value) {
                    this.ovShortnam = value;
                }

                /**
                 * Gets the value of the ovShortname property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOvShortname() {
                    return ovShortname;
                }

                /**
                 * Sets the value of the ovShortname property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOvShortname(String value) {
                    this.ovShortname = value;
                }

                /**
                 * Gets the value of the ovName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOvName() {
                    return ovName;
                }

                /**
                 * Sets the value of the ovName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOvName(String value) {
                    this.ovName = value;
                }

                /**
                 * Gets the value of the ovDescription property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOvDescription() {
                    return ovDescription;
                }

                /**
                 * Sets the value of the ovDescription property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOvDescription(String value) {
                    this.ovDescription = value;
                }

                /**
                 * Gets the value of the ovType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOvType() {
                    return ovType;
                }

                /**
                 * Sets the value of the ovType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOvType(String value) {
                    this.ovType = value;
                }
                @Override
                public String toString()
                {
                    return "OutputVariable: [Ov_Order = "+ovOrder+", Ov_Shortnam = "+ovShortnam+", Ov_Name = "+ovName+", Ov_Description = "+ovDescription+", Ov_Shortname = "+ovShortname+", Ov_Type = "+ovType+"]";
                }

            }
            @Override
        	public String toString() {
        		return "Method: [Input_Parameter = " + inputParameter + ", Output_Variable = " + outputVariable
        				+ ", Description = " + description + ", Input_Variable = " + inputVariable + ", Label = " + label
        				+ ", Shortname = " + shortname + ", Name = " + name + "]";
        	}

        }
        @Override
    	public String toString() {
    		return "Methods: [Method = " + method + "]";
    	}

    }
    @Override
    public String toString()
    {
        return "Service: [Description = "+description +", Language = "+language+", Filename = "+filename+", Shortname = "+shortname+", Methods = "+methods+", Name = "+name+"]";
    }

}
